import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1790440199128 implements MigrationInterface {
    name = 'InitialSchema1790440199128'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`address\` (\`id\` int NOT NULL AUTO_INCREMENT, \`num\` int NOT NULL, \`street\` varchar(100) NOT NULL, \`neighborhood\` varchar(100) NOT NULL, \`city\` varchar(100) NOT NULL, \`state\` varchar(100) NOT NULL, \`country\` varchar(100) NOT NULL, \`postalCode\` varchar(20) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`invites\` (\`id\` int NOT NULL AUTO_INCREMENT, \`code\` varchar(16) NOT NULL, \`kind\` varchar(10) NOT NULL, \`inviterRole\` varchar(10) NOT NULL, \`context\` varchar(120) NOT NULL DEFAULT '', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`inviterId\` int NULL, INDEX \`IDX_2b0220bc366895412d19b9aa41\` (\`inviterId\`, \`kind\`, \`context\`), UNIQUE INDEX \`IDX_33fd8a248db1cd832baa8aa25b\` (\`code\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`categories\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(100) NOT NULL, \`description\` varchar(400) NOT NULL, \`subcategories\` json NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`payments\` (\`id\` int NOT NULL AUTO_INCREMENT, \`amount\` decimal(10,2) NOT NULL, \`feePercent\` decimal(5,2) NOT NULL, \`fee\` decimal(10,2) NOT NULL, \`net\` decimal(10,2) NOT NULL, \`method\` enum ('pix', 'cartao', 'boleto') NOT NULL, \`status\` enum ('PAGO', 'LIBERADO', 'ESTORNADO') NOT NULL DEFAULT 'PAGO', \`transactionCode\` varchar(40) NOT NULL, \`paidAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`releasedAt\` datetime NULL, \`refundedAt\` datetime NULL, \`hireId\` int NULL, \`providerId\` int NULL, \`userId\` int NULL, UNIQUE INDEX \`REL_36492b46162ee9807e700307c2\` (\`hireId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`contracts\` (\`id\` int NOT NULL AUTO_INCREMENT, \`code\` varchar(100) NOT NULL, \`firstContact\` date NOT NULL, \`lastContact\` date NOT NULL, \`price\` double NOT NULL, \`description_service\` varchar(100) NOT NULL, \`clientSignature\` json NULL, \`providerSignature\` json NULL, \`providerId\` int NULL, \`hireId\` int NULL, \`userId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`hires\` (\`id\` int NOT NULL AUTO_INCREMENT, \`firstContact\` date NOT NULL, \`price\` double NOT NULL, \`description_service\` varchar(100) NOT NULL, \`packageName\` varchar(40) NULL, \`quantity\` double NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`acceptedAt\` datetime NULL, \`cancelledBy\` varchar(20) NULL, \`cancelReason\` varchar(300) NULL, \`scheduledAt\` datetime NULL, \`rescheduleTo\` datetime NULL, \`rescheduleBy\` varchar(20) NULL, \`disputed\` tinyint NOT NULL DEFAULT 0, \`lateCancel\` tinyint NOT NULL DEFAULT 0, \`serviceAddress\` json NULL, \`startedAt\` datetime NULL, \`finishedAt\` datetime NULL, \`confirmedAt\` datetime NULL, \`durationMinutes\` int NULL, \`status\` enum ('PENDENTE', 'ACEITO', 'EM ANDAMENTO', 'CONCLUIDO', 'CANCELADO') NOT NULL DEFAULT 'PENDENTE', \`status_provider\` enum ('PENDENTE', 'ACEITO', 'EM ANDAMENTO', 'CONCLUIDO', 'CANCELADO') NOT NULL DEFAULT 'PENDENTE', \`paymentRequired\` tinyint NOT NULL DEFAULT 0, \`userId\` int NULL, \`providerId\` int NULL, \`serviceId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`services\` (\`id\` int NOT NULL AUTO_INCREMENT, \`title\` varchar(100) NOT NULL, \`description_service\` varchar(250) NOT NULL, \`negotiable\` tinyint NOT NULL, \`requiresScheduling\` tinyint NOT NULL, \`online\` tinyint NOT NULL DEFAULT 0, \`price\` double NOT NULL, \`duration\` varchar(100) NOT NULL, \`subcategory\` varchar(200) NOT NULL DEFAULT 'Has no subcategory', \`likesNumber\` int NOT NULL DEFAULT '0', \`priceUnit\` varchar(20) NOT NULL DEFAULT 'fixo', \`packages\` json NULL, \`active\` tinyint NOT NULL DEFAULT 1, \`imageUrl\` varchar(255) NULL, \`images\` json NULL, \`scheduleSlots\` json NULL, \`cancellationNotice\` varchar(100) NULL, \`providerId\` int NULL, \`category_id\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`subcategories\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`providerId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`availabilities\` (\`id\` int NOT NULL AUTO_INCREMENT, \`day\` varchar(255) NOT NULL, \`start\` varchar(10) NOT NULL, \`end\` varchar(10) NOT NULL, \`providerId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`links\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`providerId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`service_providers\` (\`id\` int NOT NULL AUTO_INCREMENT, \`professionalName\` varchar(255) NOT NULL, \`companyName\` varchar(100) NOT NULL, \`professionalEmail\` varchar(255) NOT NULL, \`professionalPhone\` varchar(255) NOT NULL, \`attendsPresent\` tinyint NOT NULL DEFAULT 0, \`attendsOnline\` tinyint NOT NULL DEFAULT 0, \`personalizedProposals\` tinyint NOT NULL DEFAULT 0, \`approximateLocation\` tinyint NOT NULL DEFAULT 0, \`publicReviews\` tinyint NOT NULL DEFAULT 0, \`pricesOnPage\` tinyint NOT NULL DEFAULT 0, \`whatsNotification\` tinyint NOT NULL DEFAULT 0, \`emailNotification\` tinyint NOT NULL DEFAULT 0, \`status\` varchar(255) NOT NULL DEFAULT 'available', \`onlineLink\` varchar(400) NULL, \`slug\` varchar(64) NULL, \`closedUntil\` datetime NULL, \`deactivatedAt\` datetime NULL, \`showContact\` tinyint NOT NULL DEFAULT 0, \`createdAt\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6), \`baseCity\` varchar(80) NULL, \`baseState\` varchar(2) NULL, \`latitude\` double NULL, \`longitude\` double NULL, \`serviceRadiusKm\` int NOT NULL DEFAULT '20', \`description\` varchar(255) NULL, \`cnpj\` varchar(18) NULL, \`businessType\` varchar(20) NOT NULL DEFAULT 'autonomo', \`legalName\` varchar(150) NULL, \`companySize\` varchar(10) NULL, \`profileImageUrl\` varchar(255) NULL, \`verificationStatus\` varchar(20) NOT NULL DEFAULT 'none', \`verificationFiles\` json NULL, \`verificationNote\` varchar(300) NULL, \`verifiedAt\` datetime NULL, \`companyVerifiedAt\` datetime NULL, \`credentialsVerifiedAt\` datetime NULL, \`userId\` int NULL, \`categoryId\` int NULL, UNIQUE INDEX \`IDX_805335f7871166960295e398f5\` (\`slug\`), UNIQUE INDEX \`REL_1198a9c099e292b51ae75dcb11\` (\`userId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(100) NOT NULL, \`email\` varchar(100) NOT NULL, \`cpf_cnpj\` varchar(14) NOT NULL, \`accountType\` varchar(20) NOT NULL DEFAULT 'cliente', \`legalName\` varchar(150) NULL, \`tradeName\` varchar(100) NULL, \`companySize\` varchar(10) NULL, \`password\` varchar(255) NOT NULL, \`acceptedTerms\` tinyint NOT NULL, \`acceptedAt\` date NULL, \`about\` varchar(400) NULL, \`emailVerified\` tinyint NOT NULL DEFAULT 0, \`emailNotifications\` tinyint NOT NULL DEFAULT 1, \`role\` varchar(20) NOT NULL DEFAULT 'user', \`blocked\` tinyint NOT NULL DEFAULT 0, \`blockedReason\` varchar(300) NULL, \`avatarUrl\` varchar(255) NULL, \`inviteConvertedAt\` datetime NULL, \`inviteId\` int NULL, \`addressId\` int NULL, UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` (\`email\`), UNIQUE INDEX \`REL_bafb08f60d7857f4670c172a6e\` (\`addressId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`review_photos\` (\`id\` int NOT NULL AUTO_INCREMENT, \`url\` varchar(255) NOT NULL, \`reviewId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`reviews\` (\`id\` int NOT NULL AUTO_INCREMENT, \`rating\` tinyint NOT NULL, \`comment\` text NULL, \`hiddenAt\` datetime NULL, \`hiddenReason\` varchar(300) NULL, \`direction\` enum ('CLIENT_TO_PROVIDER', 'PROVIDER_TO_CLIENT') NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`authorId\` int NULL, \`targetId\` int NULL, \`providerId\` int NULL, \`serviceId\` int NULL, \`hireId\` int NULL, UNIQUE INDEX \`IDX_3d3985e522f38c72083abbaf16\` (\`hireId\`, \`direction\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`service_likes\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`userId\` int NULL, \`serviceId\` int NULL, UNIQUE INDEX \`IDX_06f2691c2731b98a4995744597\` (\`userId\`, \`serviceId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`messages\` (\`id\` int NOT NULL AUTO_INCREMENT, \`role\` enum ('cliente', 'prestador', 'system') NOT NULL, \`text\` text NOT NULL, \`attachmentUrl\` varchar(255) NULL, \`attachmentName\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`conversationId\` int NULL, \`senderId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`conversations\` (\`id\` int NOT NULL AUTO_INCREMENT, \`status\` enum ('OPEN', 'FORMALIZED', 'CLOSED') NOT NULL DEFAULT 'OPEN', \`topics\` json NULL, \`request\` json NULL, \`requestStatus\` enum ('PENDENTE', 'RESPONDIDA', 'RECUSADA') NULL, \`rejectReason\` varchar(500) NULL, \`closedBy\` varchar(20) NULL, \`closeReason\` varchar(500) NULL, \`clientAcceptedAt\` datetime NULL, \`providerAcceptedAt\` datetime NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`clientId\` int NULL, \`providerId\` int NULL, \`serviceId\` int NULL, \`hireId\` int NULL, \`contractId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`notifications\` (\`id\` int NOT NULL AUTO_INCREMENT, \`type\` varchar(40) NOT NULL, \`title\` varchar(120) NOT NULL, \`body\` varchar(300) NOT NULL DEFAULT '', \`link\` varchar(120) NOT NULL DEFAULT '', \`read\` tinyint NOT NULL DEFAULT 0, \`emailed\` tinyint NOT NULL DEFAULT 0, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`userId\` int NULL, INDEX \`IDX_d60c47e715847c8aa792ba6d1e\` (\`userId\`, \`read\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`auth_tokens\` (\`id\` int NOT NULL AUTO_INCREMENT, \`type\` varchar(20) NOT NULL, \`tokenHash\` varchar(64) NOT NULL, \`expiresAt\` datetime NOT NULL, \`usedAt\` datetime NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`userId\` int NULL, UNIQUE INDEX \`IDX_323c4ca6708c6a8b81af2b4ee0\` (\`tokenHash\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`reports\` (\`id\` int NOT NULL AUTO_INCREMENT, \`reason\` varchar(30) NOT NULL, \`description\` varchar(1000) NOT NULL, \`files\` json NULL, \`status\` varchar(20) NOT NULL DEFAULT 'ABERTA', \`resolution\` varchar(500) NULL, \`resolvedAt\` datetime NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`reporterId\` int NULL, \`hireId\` int NULL, \`providerId\` int NULL, \`resolvedById\` int NULL, INDEX \`IDX_dab4d78b3be05c1ca4a626f57f\` (\`status\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`portfolio_items\` (\`id\` int NOT NULL AUTO_INCREMENT, \`imageUrl\` varchar(255) NOT NULL, \`title\` varchar(80) NOT NULL, \`description\` varchar(300) NOT NULL DEFAULT '', \`position\` int NOT NULL DEFAULT '0', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`providerId\` int NULL, \`serviceId\` int NULL, INDEX \`IDX_fc53234a1c7d0b406a8352032f\` (\`providerId\`, \`position\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`analytics_daily\` (\`id\` int NOT NULL AUTO_INCREMENT, \`day\` date NOT NULL, \`event\` varchar(40) NOT NULL, \`providerId\` int NOT NULL DEFAULT '0', \`serviceId\` int NOT NULL DEFAULT '0', \`source\` varchar(20) NOT NULL DEFAULT 'direct', \`count\` int NOT NULL DEFAULT '0', INDEX \`IDX_ac59c563bccd7f6d9c9f0470f8\` (\`providerId\`, \`day\`), UNIQUE INDEX \`IDX_694f9a07f8f92285dff495ee2e\` (\`day\`, \`event\`, \`providerId\`, \`serviceId\`, \`source\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`support_tickets\` (\`id\` int NOT NULL AUTO_INCREMENT, \`category\` varchar(20) NOT NULL, \`subject\` varchar(120) NOT NULL, \`message\` varchar(2000) NOT NULL, \`status\` varchar(20) NOT NULL DEFAULT 'ABERTO', \`reply\` varchar(2000) NULL, \`answeredAt\` datetime NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`userId\` int NULL, \`answeredById\` int NULL, INDEX \`IDX_ba7b1a2ed4051fb3b39ff95444\` (\`status\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`provider_favorites\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`userId\` int NULL, \`providerId\` int NULL, UNIQUE INDEX \`IDX_d8f473af7e1185acf6fbc1eaa6\` (\`userId\`, \`providerId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`invites\` ADD CONSTRAINT \`FK_fba2934931761bc4c620e1b180f\` FOREIGN KEY (\`inviterId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD CONSTRAINT \`FK_36492b46162ee9807e700307c2b\` FOREIGN KEY (\`hireId\`) REFERENCES \`hires\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD CONSTRAINT \`FK_a25d33dbd8e95a1875d42ac40c3\` FOREIGN KEY (\`providerId\`) REFERENCES \`service_providers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD CONSTRAINT \`FK_d35cb3c13a18e1ea1705b2817b1\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`contracts\` ADD CONSTRAINT \`FK_e215116b89a36d17ed973623fdf\` FOREIGN KEY (\`providerId\`) REFERENCES \`service_providers\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`contracts\` ADD CONSTRAINT \`FK_d7a2ac43ff16e2ecc7b9b61d5e5\` FOREIGN KEY (\`hireId\`) REFERENCES \`hires\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`contracts\` ADD CONSTRAINT \`FK_4f178b72ba6f1e74f6643d86c11\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`hires\` ADD CONSTRAINT \`FK_6a072c16d4da771ffa83570ffae\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`hires\` ADD CONSTRAINT \`FK_7ffa2e981493626ad2fb3af1b73\` FOREIGN KEY (\`providerId\`) REFERENCES \`service_providers\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`hires\` ADD CONSTRAINT \`FK_b6e7abcb7e6a0532f48d77ae26c\` FOREIGN KEY (\`serviceId\`) REFERENCES \`services\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`services\` ADD CONSTRAINT \`FK_8b619ef0a4fe392dbde07eee1e2\` FOREIGN KEY (\`providerId\`) REFERENCES \`service_providers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`services\` ADD CONSTRAINT \`FK_1f8d1173481678a035b4a81a4ec\` FOREIGN KEY (\`category_id\`) REFERENCES \`categories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`subcategories\` ADD CONSTRAINT \`FK_72c44a013ad85c5cf7bb5f208f2\` FOREIGN KEY (\`providerId\`) REFERENCES \`service_providers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`availabilities\` ADD CONSTRAINT \`FK_cf35313316830a0b3dd1d3c1aee\` FOREIGN KEY (\`providerId\`) REFERENCES \`service_providers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`links\` ADD CONSTRAINT \`FK_c99e842a791a8935712810582d9\` FOREIGN KEY (\`providerId\`) REFERENCES \`service_providers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`service_providers\` ADD CONSTRAINT \`FK_1198a9c099e292b51ae75dcb11f\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`service_providers\` ADD CONSTRAINT \`FK_2b5cd162b526c14dc8ca47d12b2\` FOREIGN KEY (\`categoryId\`) REFERENCES \`categories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_f2c622b23af6c1067ebc5706475\` FOREIGN KEY (\`inviteId\`) REFERENCES \`invites\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_bafb08f60d7857f4670c172a6ea\` FOREIGN KEY (\`addressId\`) REFERENCES \`address\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`review_photos\` ADD CONSTRAINT \`FK_73428832f4d647dc22aefe3109e\` FOREIGN KEY (\`reviewId\`) REFERENCES \`reviews\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD CONSTRAINT \`FK_48770372f891b9998360e4434f3\` FOREIGN KEY (\`authorId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD CONSTRAINT \`FK_4a73980338b57f2c9178d8aaeb9\` FOREIGN KEY (\`targetId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD CONSTRAINT \`FK_4c29faa8169d9741d3a1d514830\` FOREIGN KEY (\`providerId\`) REFERENCES \`service_providers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD CONSTRAINT \`FK_9563540c43639a0669f68e8ebe3\` FOREIGN KEY (\`serviceId\`) REFERENCES \`services\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD CONSTRAINT \`FK_79f6a7f9cce03625301bbfe9776\` FOREIGN KEY (\`hireId\`) REFERENCES \`hires\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`service_likes\` ADD CONSTRAINT \`FK_59dedfeef76399813884b3412eb\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`service_likes\` ADD CONSTRAINT \`FK_d4b18004e5564e7f10227c75c94\` FOREIGN KEY (\`serviceId\`) REFERENCES \`services\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD CONSTRAINT \`FK_e5663ce0c730b2de83445e2fd19\` FOREIGN KEY (\`conversationId\`) REFERENCES \`conversations\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD CONSTRAINT \`FK_2db9cf2b3ca111742793f6c37ce\` FOREIGN KEY (\`senderId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`conversations\` ADD CONSTRAINT \`FK_2882c536d4eecfd496132b20eeb\` FOREIGN KEY (\`clientId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`conversations\` ADD CONSTRAINT \`FK_63d29283720d89a851483cdb1c5\` FOREIGN KEY (\`providerId\`) REFERENCES \`service_providers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`conversations\` ADD CONSTRAINT \`FK_da32239f974af5fbd7c9d9537bb\` FOREIGN KEY (\`serviceId\`) REFERENCES \`services\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`conversations\` ADD CONSTRAINT \`FK_6deabbc336f9adf3c5217b0ae08\` FOREIGN KEY (\`hireId\`) REFERENCES \`hires\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`conversations\` ADD CONSTRAINT \`FK_9f8da9224671e53f0cc71e2366e\` FOREIGN KEY (\`contractId\`) REFERENCES \`contracts\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD CONSTRAINT \`FK_692a909ee0fa9383e7859f9b406\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`auth_tokens\` ADD CONSTRAINT \`FK_c25fb956ebada4b256501585cca\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reports\` ADD CONSTRAINT \`FK_4353be8309ce86650def2f8572d\` FOREIGN KEY (\`reporterId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reports\` ADD CONSTRAINT \`FK_cfcd50ea3feab4357224e5e250e\` FOREIGN KEY (\`hireId\`) REFERENCES \`hires\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reports\` ADD CONSTRAINT \`FK_7f311288480efce066835e6bbbc\` FOREIGN KEY (\`providerId\`) REFERENCES \`service_providers\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reports\` ADD CONSTRAINT \`FK_96c48f2061ac14169c54a3f2d0e\` FOREIGN KEY (\`resolvedById\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`portfolio_items\` ADD CONSTRAINT \`FK_f2b1a00f9204b92323b646f8543\` FOREIGN KEY (\`providerId\`) REFERENCES \`service_providers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`portfolio_items\` ADD CONSTRAINT \`FK_49bdb1b186210494288c62dc3d3\` FOREIGN KEY (\`serviceId\`) REFERENCES \`services\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`support_tickets\` ADD CONSTRAINT \`FK_8679e2ff150ff0e253189ca0253\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`support_tickets\` ADD CONSTRAINT \`FK_cf68860d9f48934e1ed003670fa\` FOREIGN KEY (\`answeredById\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`provider_favorites\` ADD CONSTRAINT \`FK_16b1b007e13fc014f730d9616e1\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`provider_favorites\` ADD CONSTRAINT \`FK_a55effeb8ddbfac092aab60527c\` FOREIGN KEY (\`providerId\`) REFERENCES \`service_providers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`provider_favorites\` DROP FOREIGN KEY \`FK_a55effeb8ddbfac092aab60527c\``);
        await queryRunner.query(`ALTER TABLE \`provider_favorites\` DROP FOREIGN KEY \`FK_16b1b007e13fc014f730d9616e1\``);
        await queryRunner.query(`ALTER TABLE \`support_tickets\` DROP FOREIGN KEY \`FK_cf68860d9f48934e1ed003670fa\``);
        await queryRunner.query(`ALTER TABLE \`support_tickets\` DROP FOREIGN KEY \`FK_8679e2ff150ff0e253189ca0253\``);
        await queryRunner.query(`ALTER TABLE \`portfolio_items\` DROP FOREIGN KEY \`FK_49bdb1b186210494288c62dc3d3\``);
        await queryRunner.query(`ALTER TABLE \`portfolio_items\` DROP FOREIGN KEY \`FK_f2b1a00f9204b92323b646f8543\``);
        await queryRunner.query(`ALTER TABLE \`reports\` DROP FOREIGN KEY \`FK_96c48f2061ac14169c54a3f2d0e\``);
        await queryRunner.query(`ALTER TABLE \`reports\` DROP FOREIGN KEY \`FK_7f311288480efce066835e6bbbc\``);
        await queryRunner.query(`ALTER TABLE \`reports\` DROP FOREIGN KEY \`FK_cfcd50ea3feab4357224e5e250e\``);
        await queryRunner.query(`ALTER TABLE \`reports\` DROP FOREIGN KEY \`FK_4353be8309ce86650def2f8572d\``);
        await queryRunner.query(`ALTER TABLE \`auth_tokens\` DROP FOREIGN KEY \`FK_c25fb956ebada4b256501585cca\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP FOREIGN KEY \`FK_692a909ee0fa9383e7859f9b406\``);
        await queryRunner.query(`ALTER TABLE \`conversations\` DROP FOREIGN KEY \`FK_9f8da9224671e53f0cc71e2366e\``);
        await queryRunner.query(`ALTER TABLE \`conversations\` DROP FOREIGN KEY \`FK_6deabbc336f9adf3c5217b0ae08\``);
        await queryRunner.query(`ALTER TABLE \`conversations\` DROP FOREIGN KEY \`FK_da32239f974af5fbd7c9d9537bb\``);
        await queryRunner.query(`ALTER TABLE \`conversations\` DROP FOREIGN KEY \`FK_63d29283720d89a851483cdb1c5\``);
        await queryRunner.query(`ALTER TABLE \`conversations\` DROP FOREIGN KEY \`FK_2882c536d4eecfd496132b20eeb\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP FOREIGN KEY \`FK_2db9cf2b3ca111742793f6c37ce\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP FOREIGN KEY \`FK_e5663ce0c730b2de83445e2fd19\``);
        await queryRunner.query(`ALTER TABLE \`service_likes\` DROP FOREIGN KEY \`FK_d4b18004e5564e7f10227c75c94\``);
        await queryRunner.query(`ALTER TABLE \`service_likes\` DROP FOREIGN KEY \`FK_59dedfeef76399813884b3412eb\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP FOREIGN KEY \`FK_79f6a7f9cce03625301bbfe9776\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP FOREIGN KEY \`FK_9563540c43639a0669f68e8ebe3\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP FOREIGN KEY \`FK_4c29faa8169d9741d3a1d514830\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP FOREIGN KEY \`FK_4a73980338b57f2c9178d8aaeb9\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP FOREIGN KEY \`FK_48770372f891b9998360e4434f3\``);
        await queryRunner.query(`ALTER TABLE \`review_photos\` DROP FOREIGN KEY \`FK_73428832f4d647dc22aefe3109e\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_bafb08f60d7857f4670c172a6ea\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_f2c622b23af6c1067ebc5706475\``);
        await queryRunner.query(`ALTER TABLE \`service_providers\` DROP FOREIGN KEY \`FK_2b5cd162b526c14dc8ca47d12b2\``);
        await queryRunner.query(`ALTER TABLE \`service_providers\` DROP FOREIGN KEY \`FK_1198a9c099e292b51ae75dcb11f\``);
        await queryRunner.query(`ALTER TABLE \`links\` DROP FOREIGN KEY \`FK_c99e842a791a8935712810582d9\``);
        await queryRunner.query(`ALTER TABLE \`availabilities\` DROP FOREIGN KEY \`FK_cf35313316830a0b3dd1d3c1aee\``);
        await queryRunner.query(`ALTER TABLE \`subcategories\` DROP FOREIGN KEY \`FK_72c44a013ad85c5cf7bb5f208f2\``);
        await queryRunner.query(`ALTER TABLE \`services\` DROP FOREIGN KEY \`FK_1f8d1173481678a035b4a81a4ec\``);
        await queryRunner.query(`ALTER TABLE \`services\` DROP FOREIGN KEY \`FK_8b619ef0a4fe392dbde07eee1e2\``);
        await queryRunner.query(`ALTER TABLE \`hires\` DROP FOREIGN KEY \`FK_b6e7abcb7e6a0532f48d77ae26c\``);
        await queryRunner.query(`ALTER TABLE \`hires\` DROP FOREIGN KEY \`FK_7ffa2e981493626ad2fb3af1b73\``);
        await queryRunner.query(`ALTER TABLE \`hires\` DROP FOREIGN KEY \`FK_6a072c16d4da771ffa83570ffae\``);
        await queryRunner.query(`ALTER TABLE \`contracts\` DROP FOREIGN KEY \`FK_4f178b72ba6f1e74f6643d86c11\``);
        await queryRunner.query(`ALTER TABLE \`contracts\` DROP FOREIGN KEY \`FK_d7a2ac43ff16e2ecc7b9b61d5e5\``);
        await queryRunner.query(`ALTER TABLE \`contracts\` DROP FOREIGN KEY \`FK_e215116b89a36d17ed973623fdf\``);
        await queryRunner.query(`ALTER TABLE \`payments\` DROP FOREIGN KEY \`FK_d35cb3c13a18e1ea1705b2817b1\``);
        await queryRunner.query(`ALTER TABLE \`payments\` DROP FOREIGN KEY \`FK_a25d33dbd8e95a1875d42ac40c3\``);
        await queryRunner.query(`ALTER TABLE \`payments\` DROP FOREIGN KEY \`FK_36492b46162ee9807e700307c2b\``);
        await queryRunner.query(`ALTER TABLE \`invites\` DROP FOREIGN KEY \`FK_fba2934931761bc4c620e1b180f\``);
        await queryRunner.query(`DROP INDEX \`IDX_d8f473af7e1185acf6fbc1eaa6\` ON \`provider_favorites\``);
        await queryRunner.query(`DROP TABLE \`provider_favorites\``);
        await queryRunner.query(`DROP INDEX \`IDX_ba7b1a2ed4051fb3b39ff95444\` ON \`support_tickets\``);
        await queryRunner.query(`DROP TABLE \`support_tickets\``);
        await queryRunner.query(`DROP INDEX \`IDX_694f9a07f8f92285dff495ee2e\` ON \`analytics_daily\``);
        await queryRunner.query(`DROP INDEX \`IDX_ac59c563bccd7f6d9c9f0470f8\` ON \`analytics_daily\``);
        await queryRunner.query(`DROP TABLE \`analytics_daily\``);
        await queryRunner.query(`DROP INDEX \`IDX_fc53234a1c7d0b406a8352032f\` ON \`portfolio_items\``);
        await queryRunner.query(`DROP TABLE \`portfolio_items\``);
        await queryRunner.query(`DROP INDEX \`IDX_dab4d78b3be05c1ca4a626f57f\` ON \`reports\``);
        await queryRunner.query(`DROP TABLE \`reports\``);
        await queryRunner.query(`DROP INDEX \`IDX_323c4ca6708c6a8b81af2b4ee0\` ON \`auth_tokens\``);
        await queryRunner.query(`DROP TABLE \`auth_tokens\``);
        await queryRunner.query(`DROP INDEX \`IDX_d60c47e715847c8aa792ba6d1e\` ON \`notifications\``);
        await queryRunner.query(`DROP TABLE \`notifications\``);
        await queryRunner.query(`DROP TABLE \`conversations\``);
        await queryRunner.query(`DROP TABLE \`messages\``);
        await queryRunner.query(`DROP INDEX \`IDX_06f2691c2731b98a4995744597\` ON \`service_likes\``);
        await queryRunner.query(`DROP TABLE \`service_likes\``);
        await queryRunner.query(`DROP INDEX \`IDX_3d3985e522f38c72083abbaf16\` ON \`reviews\``);
        await queryRunner.query(`DROP TABLE \`reviews\``);
        await queryRunner.query(`DROP TABLE \`review_photos\``);
        await queryRunner.query(`DROP INDEX \`REL_bafb08f60d7857f4670c172a6e\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\` ON \`users\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP INDEX \`REL_1198a9c099e292b51ae75dcb11\` ON \`service_providers\``);
        await queryRunner.query(`DROP INDEX \`IDX_805335f7871166960295e398f5\` ON \`service_providers\``);
        await queryRunner.query(`DROP TABLE \`service_providers\``);
        await queryRunner.query(`DROP TABLE \`links\``);
        await queryRunner.query(`DROP TABLE \`availabilities\``);
        await queryRunner.query(`DROP TABLE \`subcategories\``);
        await queryRunner.query(`DROP TABLE \`services\``);
        await queryRunner.query(`DROP TABLE \`hires\``);
        await queryRunner.query(`DROP TABLE \`contracts\``);
        await queryRunner.query(`DROP INDEX \`REL_36492b46162ee9807e700307c2\` ON \`payments\``);
        await queryRunner.query(`DROP TABLE \`payments\``);
        await queryRunner.query(`DROP TABLE \`categories\``);
        await queryRunner.query(`DROP INDEX \`IDX_33fd8a248db1cd832baa8aa25b\` ON \`invites\``);
        await queryRunner.query(`DROP INDEX \`IDX_2b0220bc366895412d19b9aa41\` ON \`invites\``);
        await queryRunner.query(`DROP TABLE \`invites\``);
        await queryRunner.query(`DROP TABLE \`address\``);
    }

}
