// Modelos de serviço para os dados de demonstração.
// Cada modelo: subcategoria, títulos (variações entre prestadores), descrição, faixa de preço,
// unidade (fixo | hora | m2 | orcamento), duração, flags e a busca de fotos (Openverse, inglês).
// o = online, s = exige agendamento, n = negociável

const T = (sub, titles, desc, price, unit, duration, flags, query) => ({ sub, titles, desc, price, unit, duration, online: flags.includes("o"), scheduling: flags.includes("s"), negotiable: flags.includes("n"), query });

export const CATALOG = {
  "Reformas e reparos": {
    weight: 12,
    bios: ["Atendo residências e comércios com pontualidade e garantia no serviço.", "Mais de 10 anos de experiência em obras e manutenção predial.", "Orçamento sem compromisso, material de qualidade e limpeza ao final."],
    names: ["Reparos", "Manutenção", "Reformas", "Obras", "Construções", "Serviços Gerais"],
    templates: [
      T("Elétrica", ["Instalação de chuveiro elétrico", "Troca de chuveiro e resistência"], "Instalação com teste de disjuntor, aterramento e fiação adequada à potência.", [90, 160], "fixo", "1 hora", "sn", "electrician installing"),
      T("Elétrica", ["Troca de quadro de disjuntores", "Adequação de quadro elétrico"], "Substituição do quadro com identificação de circuitos e DR para segurança.", [380, 900], "fixo", "4 horas", "n", "electrical panel breaker"),
      T("Hidráulica", ["Conserto de vazamento", "Caça-vazamento e reparo"], "Localização do vazamento, reparo na tubulação e teste de pressão.", [120, 260], "fixo", "2 horas", "sn", "plumber fixing pipe"),
      T("Hidráulica", ["Desentupimento de pia e ralo", "Desentupimento residencial"], "Desentupimento com equipamento profissional, sem quebrar pisos.", [100, 220], "fixo", "1 hora", "n", "plumbing sink repair"),
      T("Pintura", ["Pintura de apartamento", "Pintura residencial interna"], "Preparação de paredes, massa corrida onde necessário e duas demãos de tinta.", [18, 35], "m2", "3 dias", "n", "house painter wall"),
      T("Alvenaria", ["Pequenas reformas e alvenaria", "Reboco, contrapiso e alvenaria"], "Levantamento de paredes, reboco, contrapiso e acabamentos.", [0, 0], "orcamento", "A combinar", "n", "bricklayer construction"),
      T("Marcenaria", ["Móveis planejados sob medida", "Marcenaria sob medida"], "Projeto 3D, fabricação e instalação de armários, painéis e cozinhas.", [0, 0], "orcamento", "A combinar", "n", "carpenter woodworking furniture"),
      T("Gesso e drywall", ["Forro de gesso e sanca", "Parede de drywall"], "Forros, sancas e divisórias em drywall com acabamento pronto para pintura.", [65, 120], "m2", "2 dias", "n", "drywall installation ceiling"),
      T("Pisos e revestimentos", ["Instalação de porcelanato", "Assentamento de pisos"], "Assentamento com nivelamento, rejunte e acabamento de rodapé.", [45, 90], "m2", "3 dias", "n", "tile floor installation"),
      T("Telhados e calhas", ["Conserto de telhado e calhas", "Limpeza e troca de calhas"], "Troca de telhas quebradas, revisão de calhas e impermeabilização.", [200, 600], "fixo", "1 dia", "n", "roofer roof repair"),
    ],
  },
  "Limpeza": {
    weight: 8,
    bios: ["Equipe treinada e produtos de qualidade para deixar tudo impecável.", "Faxina detalhada com carinho e atenção a cada canto da casa.", "Atendo casas, apartamentos e escritórios com agendamento flexível."],
    names: ["Limpeza", "Clean", "Faxinas", "Brilho", "Higienização"],
    templates: [
      T("Residencial", ["Faxina residencial completa", "Diarista para casa e apartamento"], "Limpeza de todos os cômodos, banheiros, cozinha, janelas internas e organização.", [160, 260], "fixo", "6 horas", "sn", "house cleaning"),
      T("Pós-obra", ["Limpeza pós-obra", "Limpeza fina pós-reforma"], "Remoção de resíduos de tinta, cimento e poeira fina, pronto para morar.", [8, 15], "m2", "1 dia", "n", "post construction cleaning"),
      T("Comercial", ["Limpeza de escritório", "Limpeza comercial semanal"], "Limpeza de estações de trabalho, copa e banheiros fora do horário comercial.", [45, 70], "hora", "4 horas", "", "office cleaning"),
      T("Estofados", ["Higienização de sofá", "Limpeza de estofados e colchões"], "Higienização a seco e extração, elimina ácaros e manchas.", [150, 320], "fixo", "2 horas", "s", "sofa upholstery cleaning"),
      T("Vidros e fachadas", ["Limpeza de vidros e janelas", "Limpeza de fachada envidraçada"], "Limpeza de vidros internos e externos com equipamentos de segurança.", [120, 400], "fixo", "3 horas", "n", "window cleaning"),
      T("Caixa d'água", ["Limpeza de caixa d'água", "Higienização de reservatório"], "Esvaziamento, escovação, desinfecção e laudo de limpeza.", [180, 300], "fixo", "3 horas", "s", "water tank cleaning"),
    ],
  },
  "Tecnologia": {
    weight: 6,
    bios: ["Desenvolvedor com foco em soluções simples que resolvem o problema.", "Suporte técnico rápido para casas e pequenas empresas.", "Projetos entregues com documentação e acompanhamento."],
    names: ["Tech", "Digital", "Sistemas", "Soluções", "Dev"],
    templates: [
      T("Suporte técnico", ["Formatação e manutenção de computador", "Suporte técnico em domicílio"], "Formatação, backup, remoção de vírus e instalação de programas.", [120, 200], "fixo", "3 horas", "s", "computer repair technician"),
      T("Desenvolvimento web", ["Criação de site institucional", "Site profissional para sua empresa"], "Site responsivo com até 5 páginas, formulário de contato e SEO básico.", [1200, 3500], "fixo", "15 dias", "on", "programmer laptop"),
      T("Desenvolvimento web", ["Loja virtual completa", "E-commerce sob medida"], "Loja com catálogo, carrinho, pagamentos e painel administrativo.", [0, 0], "orcamento", "A combinar", "on", "online shopping website"),
      T("Aplicativos", ["Desenvolvimento de aplicativo", "App para Android e iOS"], "Do protótipo à publicação nas lojas, com manutenção inclusa por 3 meses.", [0, 0], "orcamento", "A combinar", "on", "mobile app development smartphone"),
      T("Redes e Wi-Fi", ["Instalação de rede Wi-Fi", "Wi-Fi mesh para casa toda"], "Projeto de cobertura, instalação de roteadores e cabeamento estruturado.", [180, 450], "fixo", "4 horas", "s", "network cables"),
      T("Automação residencial", ["Automação residencial", "Casa inteligente: luzes e câmeras"], "Integração de iluminação, tomadas e câmeras com assistentes de voz.", [0, 0], "orcamento", "A combinar", "n", "smart home automation"),
    ],
  },
  "Aulas": {
    weight: 7,
    bios: ["Aulas com metodologia personalizada para o seu ritmo.", "Professor(a) com experiência em escolas e cursinhos.", "Aulas presenciais ou online, com material de apoio incluso."],
    names: ["Aulas", "Ensino", "Educação", "Escola", "Tutoria"],
    templates: [
      T("Reforço escolar", ["Reforço escolar de matemática", "Aulas particulares de matemática"], "Reforço para ensino fundamental e médio, com exercícios e simulados.", [60, 90], "hora", "1 hora", "os", "math tutor student"),
      T("Idiomas", ["Aulas de inglês", "Inglês para conversação"], "Aulas focadas em conversação, com material digital e acompanhamento.", [70, 120], "hora", "1 hora", "os", "english language class"),
      T("Idiomas", ["Aulas de espanhol", "Espanhol para viagem e trabalho"], "Do básico ao avançado, com preparação para provas de proficiência.", [60, 100], "hora", "1 hora", "os", "spanish teacher lesson"),
      T("Música", ["Aulas de violão", "Violão para iniciantes"], "Aprenda acordes, ritmos e suas músicas favoritas desde a primeira aula.", [70, 110], "hora", "1 hora", "os", "guitar lesson"),
      T("Música", ["Aulas de piano e teclado", "Piano clássico e popular"], "Leitura de partitura, técnica e repertório popular.", [80, 130], "hora", "1 hora", "s", "piano lesson"),
      T("Programação", ["Aulas de programação", "Aprenda Python do zero"], "Lógica de programação e projetos práticos em Python ou JavaScript.", [80, 140], "hora", "1 hora", "os", "programming class laptop"),
      T("Pré-vestibular", ["Preparatório para o ENEM", "Redação para o ENEM"], "Correção de redações semanais e revisão dos conteúdos mais cobrados.", [70, 110], "hora", "1 hora", "os", "students studying exam"),
    ],
  },
  "Beleza e estética": {
    weight: 8,
    bios: ["Atendimento em estúdio ou a domicílio, com hora marcada.", "Profissional certificada, apaixonada por realçar a beleza de cada cliente.", "Produtos de qualidade e materiais esterilizados."],
    names: ["Studio", "Beauty", "Espaço", "Salão", "Barbearia"],
    templates: [
      T("Cabeleireiro", ["Corte e escova", "Corte feminino"], "Corte personalizado com lavagem, hidratação rápida e finalização.", [60, 140], "fixo", "1 hora", "s", "hairdresser haircut salon"),
      T("Cabeleireiro", ["Coloração e mechas", "Luzes e morena iluminada"], "Coloração com produtos profissionais e tratamento pós-química.", [180, 450], "fixo", "3 horas", "sn", "hair coloring salon"),
      T("Barbearia", ["Corte masculino e barba", "Barba completa com toalha quente"], "Corte na máquina e tesoura, barba modelada e acabamento com navalha.", [45, 80], "fixo", "1 hora", "s", "barber shop"),
      T("Manicure e pedicure", ["Manicure e pedicure", "Unhas em gel"], "Cutilagem, esmaltação e hidratação. Alongamento em gel sob consulta.", [45, 120], "fixo", "1 hora", "s", "manicure nails"),
      T("Maquiagem", ["Maquiagem para eventos", "Maquiagem de noiva"], "Maquiagem de longa duração com prova antecipada para noivas.", [150, 600], "fixo", "2 horas", "sn", "makeup artist bride"),
      T("Sobrancelhas e cílios", ["Design de sobrancelhas", "Extensão de cílios"], "Design com henna ou extensão fio a fio, de acordo com o formato do rosto.", [40, 180], "fixo", "1 hora", "s", "eyebrow eyelash beauty"),
      T("Estética facial", ["Limpeza de pele", "Limpeza de pele profunda"], "Higienização, extração, máscara calmante e hidratação.", [120, 220], "fixo", "1 hora", "s", "facial skin care spa"),
    ],
  },
  "Saúde e bem-estar": {
    weight: 7,
    bios: ["Profissional registrado(a) no conselho, com atendimento humanizado.", "Treinos e cuidados adaptados ao seu objetivo e rotina.", "Atendimento em consultório, a domicílio ou online."],
    names: ["Saúde", "Bem-Estar", "Vida", "Equilíbrio", "Movimento"],
    templates: [
      T("Personal trainer", ["Personal trainer", "Treino funcional personalizado"], "Avaliação física, planilha de treino e acompanhamento semanal.", [80, 150], "hora", "1 hora", "s", "personal trainer fitness"),
      T("Fisioterapia", ["Fisioterapia domiciliar", "Fisioterapia ortopédica"], "Reabilitação pós-cirúrgica, dores lombares e fortalecimento.", [120, 200], "fixo", "1 hora", "s", "physiotherapy patient"),
      T("Nutrição", ["Consulta com nutricionista", "Plano alimentar personalizado"], "Anamnese, bioimpedância e plano alimentar com retorno em 30 dias.", [150, 280], "fixo", "1 hora", "os", "nutritionist healthy food"),
      T("Massoterapia", ["Massagem relaxante", "Massagem terapêutica"], "Técnicas de relaxamento e liberação miofascial com óleos essenciais.", [100, 180], "fixo", "1 hora", "s", "massage therapy"),
      T("Yoga e pilates", ["Aulas de yoga", "Pilates em grupo"], "Aulas para todos os níveis, com foco em respiração, postura e flexibilidade.", [50, 90], "hora", "1 hora", "os", "yoga class"),
      T("Psicologia", ["Psicoterapia online", "Terapia cognitivo-comportamental"], "Sessões semanais com sigilo e acolhimento, adultos e adolescentes.", [120, 220], "fixo", "50 minutos", "os", "therapy counseling session"),
    ],
  },
  "Eventos": {
    weight: 7,
    bios: ["Transformamos o seu evento em um momento inesquecível.", "Equipe completa para casamentos, aniversários e eventos corporativos.", "Atendemos toda a região metropolitana."],
    names: ["Eventos", "Festas", "Celebrações", "Produções", "Buffet"],
    templates: [
      T("Buffet", ["Buffet completo para festas", "Buffet de churrasco"], "Cardápio personalizado com salgados, pratos quentes, bebidas e equipe.", [55, 120], "fixo", "5 horas", "n", "catering buffet food"),
      T("DJ e som", ["DJ para festas e casamentos", "Som e iluminação para eventos"], "Equipamento completo de som e luz, playlist montada com os noivos.", [800, 2500], "fixo", "6 horas", "n", "dj party music"),
      T("Decoração", ["Decoração de aniversário", "Decoração de casamento"], "Mesa temática, balões, flores e painel personalizado.", [450, 3000], "fixo", "1 dia", "n", "party decoration table"),
      T("Garçom e recepção", ["Garçom para eventos", "Equipe de recepção"], "Profissionais uniformizados para servir, repor e receber convidados.", [150, 250], "fixo", "5 horas", "", "waiter serving event"),
      T("Animação infantil", ["Animação de festa infantil", "Recreação e personagens"], "Brincadeiras, pintura facial e personagens para crianças de 2 a 10 anos.", [350, 900], "fixo", "3 horas", "n", "children party entertainment"),
      T("Bartender", ["Bartender e drinks", "Open bar de drinks"], "Carta de drinks autorais, bar montado e bartender profissional.", [600, 2200], "fixo", "5 horas", "n", "bartender cocktails"),
    ],
  },
  "Pets": {
    weight: 6,
    bios: ["Amor e cuidado com o seu pet como se fosse da família.", "Profissional com cursos de comportamento animal.", "Atendimento a domicílio com transporte seguro."],
    names: ["Pet", "Pets", "Patinhas", "Cão & Gato", "Bicho"],
    templates: [
      T("Banho e tosa", ["Banho e tosa", "Tosa higiênica e banho"], "Banho com produtos hipoalergênicos, secagem, tosa e corte de unhas.", [60, 140], "fixo", "2 horas", "s", "dog grooming"),
      T("Passeador de cães", ["Passeio com cães", "Dog walker"], "Passeios de 1 hora com relatório e fotos, até 3 cães por vez.", [35, 60], "fixo", "1 hora", "s", "dog walker walking dogs"),
      T("Adestramento", ["Adestramento de cães", "Adestramento positivo"], "Comandos básicos, socialização e correção de comportamentos.", [120, 200], "fixo", "1 hora", "s", "dog training"),
      T("Pet sitter", ["Pet sitter em domicílio", "Cuidador de gatos"], "Visitas para alimentação, limpeza da caixa de areia e brincadeiras.", [50, 90], "fixo", "1 hora", "s", "cat pet sitter"),
      T("Veterinário a domicílio", ["Consulta veterinária em casa", "Vacinação a domicílio"], "Consultas, vacinas e exames sem o estresse do deslocamento.", [180, 320], "fixo", "1 hora", "s", "veterinarian dog"),
    ],
  },
  "Automotivo": {
    weight: 6,
    bios: ["Oficina com diagnóstico computadorizado e garantia.", "Atendimento rápido e peças de procedência.", "Serviço de leva e traz para sua comodidade."],
    names: ["Auto", "Car", "Mecânica", "Motors", "Garage"],
    templates: [
      T("Mecânica", ["Revisão completa do carro", "Troca de óleo e filtros"], "Troca de óleo, filtros, checagem de freios, suspensão e fluidos.", [180, 450], "fixo", "3 horas", "sn", "car mechanic engine"),
      T("Funilaria e pintura", ["Funilaria e pintura", "Martelinho de ouro"], "Reparo de amassados sem pintura e pintura com cabine.", [0, 0], "orcamento", "A combinar", "n", "car body paint shop"),
      T("Lavagem e estética", ["Lavagem detalhada", "Polimento e vitrificação"], "Lavagem técnica, higienização interna, polimento e proteção da pintura.", [90, 650], "fixo", "4 horas", "s", "car detailing wash"),
      T("Elétrica automotiva", ["Elétrica automotiva", "Troca de bateria em domicílio"], "Diagnóstico elétrico, bateria, alternador e som automotivo.", [120, 350], "fixo", "2 horas", "n", "car battery electrical"),
      T("Guincho", ["Guincho 24 horas", "Reboque de veículos"], "Atendimento 24h para carros de passeio e utilitários.", [150, 400], "fixo", "1 hora", "n", "tow truck"),
      T("Pneus e alinhamento", ["Alinhamento e balanceamento", "Troca de pneus"], "Alinhamento 3D, balanceamento e rodízio de pneus.", [80, 160], "fixo", "1 hora", "s", "car tire change"),
    ],
  },
  "Jardinagem e paisagismo": {
    weight: 5,
    bios: ["Jardins saudáveis e bem cuidados o ano todo.", "Projetos de paisagismo que combinam com o seu espaço.", "Manutenção mensal com preço fixo."],
    names: ["Jardins", "Verde", "Paisagismo", "Flora", "Garden"],
    templates: [
      T("Manutenção de jardim", ["Manutenção de jardim", "Corte de grama e poda"], "Corte de grama, poda de arbustos, adubação e limpeza.", [120, 280], "fixo", "4 horas", "s", "gardener lawn mowing"),
      T("Paisagismo", ["Projeto de paisagismo", "Jardim vertical"], "Projeto, escolha de espécies e implantação do jardim.", [0, 0], "orcamento", "A combinar", "n", "landscape garden design"),
      T("Poda de árvores", ["Poda de árvores", "Remoção de árvores"], "Poda técnica com equipamentos de segurança e retirada dos resíduos.", [250, 900], "fixo", "1 dia", "n", "tree pruning arborist"),
      T("Horta e pomar", ["Montagem de horta", "Horta em apartamento"], "Canteiros, vasos, substrato e mudas para você colher em casa.", [200, 600], "fixo", "4 horas", "", "vegetable garden planting"),
      T("Irrigação", ["Irrigação automática", "Sistema de gotejamento"], "Projeto e instalação de irrigação com timer programável.", [400, 1500], "fixo", "1 dia", "n", "garden irrigation sprinkler"),
    ],
  },
  "Mudanças e fretes": {
    weight: 5,
    bios: ["Mudanças com cuidado, embalagem e montagem inclusos.", "Caminhões de vários tamanhos e equipe treinada.", "Atendemos capital, região metropolitana e interior."],
    names: ["Mudanças", "Fretes", "Transportes", "Carretos", "Logística"],
    templates: [
      T("Frete", ["Frete pequeno", "Frete com ajudante"], "Transporte de móveis e caixas com ajudante para carregar.", [150, 350], "fixo", "3 horas", "sn", "moving truck delivery"),
      T("Mudança residencial", ["Mudança residencial completa", "Mudança com embalagem"], "Embalagem, desmontagem, transporte e montagem no novo endereço.", [0, 0], "orcamento", "A combinar", "n", "moving boxes house"),
      T("Montagem de móveis", ["Montagem de móveis", "Montador de móveis"], "Montagem e desmontagem de guarda-roupas, camas, cozinhas e escritórios.", [80, 250], "fixo", "3 horas", "s", "furniture assembly"),
      T("Carreto", ["Carreto de entulho", "Retirada de entulho"], "Retirada de entulho e móveis velhos com descarte correto.", [180, 400], "fixo", "2 horas", "", "construction debris truck"),
    ],
  },
  "Design e criatividade": {
    weight: 6,
    bios: ["Criação com estratégia: marcas que comunicam e vendem.", "Portfólio com mais de 200 projetos entregues.", "Trabalho 100% online, com revisões inclusas."],
    names: ["Design", "Criativo", "Studio", "Estúdio", "Arte"],
    templates: [
      T("Identidade visual", ["Criação de logotipo", "Identidade visual completa"], "Logo, paleta de cores, tipografia e manual de marca.", [450, 2500], "fixo", "10 dias", "on", "graphic designer"),
      T("Design gráfico", ["Artes para redes sociais", "Design de cardápio"], "Pacote de artes para posts, stories e materiais impressos.", [250, 900], "fixo", "5 dias", "on", "graphic design work"),
      T("Ilustração", ["Ilustração personalizada", "Retrato ilustrado"], "Ilustrações digitais para livros, produtos ou presentes.", [180, 800], "fixo", "7 dias", "on", "illustrator drawing"),
      T("Edição de vídeo", ["Edição de vídeos para YouTube", "Edição de reels"], "Cortes, legendas, trilha e motion básico para redes.", [120, 600], "fixo", "3 dias", "on", "video editing"),
      T("Social media", ["Gestão de redes sociais", "Social media mensal"], "Planejamento, criação de conteúdo e relatórios mensais.", [900, 2200], "fixo", "30 dias", "on", "social media marketing"),
      T("Design de interiores", ["Projeto de interiores", "Consultoria de decoração"], "Layout, escolha de móveis, iluminação e lista de compras.", [0, 0], "orcamento", "A combinar", "n", "interior design living room"),
    ],
  },
  "Fotografia e vídeo": {
    weight: 5,
    bios: ["Fotos que contam histórias, com edição profissional.", "Equipamento profissional e entrega rápida em galeria online.", "Cobertura de eventos e ensaios em estúdio ou externos."],
    names: ["Fotografia", "Photo", "Imagens", "Filmes", "Visual"],
    templates: [
      T("Ensaio fotográfico", ["Ensaio fotográfico externo", "Ensaio gestante"], "Ensaio de 1h30 com 40 fotos editadas em alta resolução.", [350, 900], "fixo", "2 horas", "sn", "photographer portrait photoshoot"),
      T("Fotografia de eventos", ["Fotografia de casamento", "Cobertura fotográfica de eventos"], "Cobertura completa com galeria online e álbum opcional.", [1500, 5000], "fixo", "8 horas", "n", "wedding photographer"),
      T("Fotografia de produtos", ["Fotos de produtos para e-commerce", "Fotografia de comida"], "Fotos com fundo infinito ou ambientadas, tratadas para lojas virtuais.", [25, 60], "fixo", "1 dia", "n", "product photography studio"),
      T("Filmagem", ["Filmagem de eventos", "Vídeo institucional"], "Captação em 4K, edição e trilha licenciada.", [900, 4000], "fixo", "1 dia", "n", "videographer camera filming"),
      T("Drone", ["Imagens aéreas com drone", "Filmagem com drone para imóveis"], "Fotos e vídeos aéreos com piloto habilitado pela ANAC.", [400, 1200], "fixo", "2 horas", "sn", "drone aerial photography"),
    ],
  },
  "Consultoria e negócios": {
    weight: 6,
    bios: ["Consultoria para pequenos negócios crescerem com segurança.", "Atendimento online para todo o Brasil.", "Linguagem simples, sem juridiquês nem contabilês."],
    names: ["Consultoria", "Assessoria", "Contábil", "Advocacia", "Negócios"],
    templates: [
      T("Contabilidade", ["Contabilidade para MEI", "Abertura de empresa"], "Abertura, declaração anual, notas fiscais e guias mensais.", [99, 450], "fixo", "30 dias", "on", "accountant office documents"),
      T("Jurídico", ["Consulta jurídica", "Revisão de contratos"], "Orientação em contratos, consumidor, trabalho e família.", [200, 600], "fixo", "1 hora", "os", "lawyer meeting"),
      T("Marketing digital", ["Gestão de tráfego pago", "Anúncios no Google e Instagram"], "Campanhas, segmentação e relatórios semanais de resultados.", [800, 2500], "fixo", "30 dias", "on", "digital marketing analytics"),
      T("Consultoria financeira", ["Organização financeira pessoal", "Planejamento financeiro"], "Diagnóstico, orçamento, controle de dívidas e investimentos.", [180, 450], "fixo", "1 hora", "os", "financial planning calculator"),
      T("Tradução", ["Tradução inglês–português", "Tradução juramentada"], "Traduções técnicas, acadêmicas e de documentos oficiais (preço por lauda).", [45, 90], "fixo", "5 dias", "on", "translation documents dictionary"),
      T("Recursos humanos", ["Recrutamento e seleção", "Consultoria de RH"], "Descrição de vagas, triagem e entrevistas para pequenas empresas.", [0, 0], "orcamento", "A combinar", "on", "job interview hiring"),
    ],
  },
  "Cuidados": {
    weight: 5,
    bios: ["Cuidado com carinho, paciência e responsabilidade.", "Experiência comprovada e referências disponíveis.", "Formação em primeiros socorros."],
    names: ["Cuidados", "Care", "Acolher", "Zelo", "Amparo"],
    templates: [
      T("Babá", ["Babá diarista", "Babá para noites e fins de semana"], "Cuidados, alimentação, brincadeiras e rotina de sono.", [25, 40], "hora", "4 horas", "s", "nanny children playing"),
      T("Cuidador de idosos", ["Cuidador de idosos", "Acompanhamento de idosos"], "Auxílio na higiene, medicação, alimentação e passeios.", [25, 45], "hora", "8 horas", "s", "elderly care caregiver"),
      T("Acompanhante hospitalar", ["Acompanhante hospitalar", "Acompanhante em consultas"], "Acompanhamento em internações, exames e consultas.", [180, 300], "fixo", "12 horas", "s", "hospital patient nurse"),
      T("Enfermagem domiciliar", ["Técnico de enfermagem a domicílio", "Curativos e aplicação de medicamentos"], "Curativos, aplicação de injetáveis e aferição de sinais vitais.", [90, 180], "fixo", "1 hora", "s", "home nurse care"),
    ],
  },
  "Moda e costura": {
    weight: 5,
    bios: ["Ajustes perfeitos para suas roupas caírem como uma luva.", "Ateliê com mais de 15 anos de experiência.", "Busca e entrega na sua casa."],
    names: ["Ateliê", "Costura", "Moda", "Alfaiataria", "Estilo"],
    templates: [
      T("Ajustes e consertos", ["Ajustes de roupas", "Barras e consertos"], "Barras, ajustes de cintura, troca de zíper e pequenos reparos.", [20, 80], "fixo", "3 dias", "", "seamstress sewing machine"),
      T("Sob medida", ["Vestido de festa sob medida", "Roupas sob medida"], "Criação de peças exclusivas com provas e acabamento de alta costura.", [0, 0], "orcamento", "A combinar", "n", "tailor dress fitting"),
      T("Personal stylist", ["Consultoria de imagem", "Personal stylist"], "Análise de estilo, organização de guarda-roupa e compras guiadas.", [300, 900], "fixo", "3 horas", "osn", "fashion stylist clothes"),
      T("Sapataria", ["Conserto de calçados", "Restauração de bolsas e sapatos"], "Troca de solado, costuras, pintura e restauração de couro.", [40, 180], "fixo", "5 dias", "", "shoemaker cobbler"),
      T("Bordado", ["Bordado personalizado", "Bordado em enxoval"], "Bordados à mão ou à máquina com nomes e desenhos.", [35, 150], "fixo", "7 dias", "", "embroidery handmade"),
    ],
  },
  "Culinária": {
    weight: 5,
    bios: ["Comida caseira feita com ingredientes frescos.", "Chef com formação e experiência em restaurantes.", "Cardápios para dietas especiais sob consulta."],
    names: ["Cozinha", "Sabores", "Gourmet", "Delícias", "Chef"],
    templates: [
      T("Chef em domicílio", ["Chef em casa", "Jantar romântico com chef"], "Menu degustação preparado e servido na sua casa, com louça lavada.", [350, 1200], "fixo", "4 horas", "sn", "chef cooking kitchen"),
      T("Marmitas", ["Marmitas fit semanais", "Marmitas congeladas"], "Kit com 10 marmitas balanceadas, entregues congeladas.", [150, 280], "fixo", "2 dias", "", "meal prep containers food"),
      T("Confeitaria", ["Bolo de aniversário", "Doces finos para festas"], "Bolos decorados e doces finos por encomenda.", [120, 600], "fixo", "3 dias", "n", "cake baking pastry"),
      T("Aulas de culinária", ["Aula de culinária em casa", "Workshop de massas"], "Aula prática com receitas, técnicas e degustação.", [180, 400], "fixo", "3 horas", "s", "cooking class"),
      T("Comida congelada", ["Kit de congelados caseiros", "Lasanhas e escondidinhos"], "Pratos caseiros congelados, prontos para aquecer.", [90, 220], "fixo", "2 dias", "", "homemade lasagna food"),
    ],
  },
  "Assistência técnica": {
    weight: 6,
    bios: ["Técnico credenciado com garantia de 90 dias.", "Atendimento no mesmo dia para a região.", "Peças originais e orçamento transparente."],
    names: ["Assistência", "Técnica", "Service", "Conserto", "Refrigeração"],
    templates: [
      T("Ar-condicionado", ["Instalação de ar-condicionado split", "Limpeza e manutenção de ar-condicionado"], "Instalação completa com suporte, tubulação e teste de gás.", [180, 650], "fixo", "4 horas", "sn", "air conditioner technician"),
      T("Eletrodomésticos", ["Conserto de máquina de lavar", "Conserto de geladeira"], "Diagnóstico no local e reparo com peças originais.", [120, 350], "fixo", "2 horas", "sn", "washing machine repair"),
      T("Celulares", ["Troca de tela de celular", "Conserto de celular"], "Troca de tela, bateria e conector com garantia.", [150, 700], "fixo", "2 horas", "n", "phone repair technician"),
      T("Computadores e notebooks", ["Manutenção de notebook", "Upgrade de SSD e memória"], "Limpeza interna, pasta térmica, SSD e memória RAM.", [120, 380], "fixo", "1 dia", "", "laptop repair"),
      T("TV e som", ["Instalação de TV na parede", "Home theater"], "Suporte, organização de cabos e configuração de som.", [120, 400], "fixo", "2 horas", "s", "tv wall mount installation"),
    ],
  },
  "Segurança": {
    weight: 5,
    bios: ["Segurança para sua casa ou empresa com tecnologia atual.", "Instalação limpa e suporte pós-venda.", "Atendimento de urgência 24h para chaveiro."],
    names: ["Segurança", "Security", "Proteção", "Alarmes", "Chaves"],
    templates: [
      T("Câmeras e alarmes", ["Instalação de câmeras de segurança", "Monitoramento por câmeras"], "Kit de câmeras HD com acesso pelo celular e gravação em nuvem.", [600, 2400], "fixo", "1 dia", "n", "security camera cctv installation"),
      T("Portões automáticos", ["Automatização de portão", "Conserto de motor de portão"], "Instalação e manutenção de motores deslizantes e basculantes.", [250, 1400], "fixo", "4 horas", "n", "automatic gate"),
      T("Chaveiro", ["Chaveiro 24 horas", "Troca de fechaduras"], "Abertura de portas, cópia de chaves e troca de fechaduras.", [60, 220], "fixo", "1 hora", "", "locksmith door lock"),
      T("Cerca elétrica", ["Instalação de cerca elétrica", "Concertina e cerca elétrica"], "Cerca elétrica com central, sirene e placas de advertência.", [700, 2200], "fixo", "1 dia", "n", "electric fence"),
      T("Interfones", ["Instalação de interfone", "Vídeo porteiro"], "Interfones e vídeo porteiros com integração ao celular.", [180, 700], "fixo", "3 horas", "", "doorbell intercom"),
    ],
  },
};
