// Gerado por scripts/landing-capture (npm run capture) a partir de backEnd/scripts/story/images.json. Não editar à mão.
// Fotos dos portfólios de demonstração (Wikimedia Commons) que aparecem nas tomadas da landing.
export const PHOTO_CREDITS: { author: string; license: string; source: string }[] = [
  { author: "Mikhail Kapychka", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Couple_from_a_Belarus_wedding.jpg" },
  { author: "Jibukrajan", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Couple_Destination_Wedding_-_Dubai.jpg" },
  { author: "Darek Novak", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Wedding_(.jpg" },
  { author: "Tom Pumford tompumford", license: "CC0", source: "https://commons.wikimedia.org/wiki/File:Tom_Pumford_2017-06-15_(Unsplash_91mRWrzT46A).jpg" },
  { author: "VonPhotography", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Dusk_wedding_portrait.jpg" },
  { author: "Geolina163", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Volksgarten_Hochzeit_Fotoshooting.jpg" },
  { author: "Shixart1985", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Chairs_are_neatly_arranged_in_a_garden_for_an_outdoor_wedding_ceremony.jpg" },
  { author: "benjgibbs", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:First_Dance_(4703822397).jpg" },
  { author: "Pasqualedifebbo", license: "CC BY 4.0", source: "https://commons.wikimedia.org/wiki/File:Primo_ballo_degli_sposi_con_sassofonista_e_macchina_sparkular.jpg" },
  { author: "Marie Miller 224", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Chicago_Riverwalk_Bride_Portrait.jpg" },
  { author: "PASAPHC2024", license: "CC0", source: "https://commons.wikimedia.org/wiki/File:Preston_Hazard_Holding_Leica_Camera_in_2025.jpg" },
  { author: "Hamster28", license: "Public domain", source: "https://commons.wikimedia.org/wiki/File:Produktfotografie_2007.jpg" },
  { author: "Stefan Krause, Germany", license: "CC BY 3.0 de", source: "https://commons.wikimedia.org/wiki/File:Schwappender_Wein.jpg" },
  { author: "Anne", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Product_photography.jpg" },
  { author: "Robertgombos", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Product_photography_34.jpg" },
  { author: "W.carter", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Necklace_made_of_rough_diamonds.jpg" },
  { author: "NadiaMalion", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Product_Photography_example.jpg" },
  { author: "Guillermo Carlos Gómez", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Legumbres.jpg" },
  { author: "A S M Jobaer", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:A_close-up_artistic_photograph_of_a_perfume_bottle_covered_in_water_droplets,_illuminated_by_dramatic_red_and_dark_lighting._03.jpg" },
  { author: "Lishkee", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Michal-Tsur-headshot.jpg" },
  { author: "Luke.O'Connor", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Head_shot_of_Luke_Drury,_Astrophysicist.jpg" },
  { author: "https://www.prashladva.com/assests/", license: "CC0", source: "https://commons.wikimedia.org/wiki/File:Dr_Prash_Ladva.jpg" },
  { author: "Norman Wong", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Pamela_Anderson_2024_Headshot_by_Norman_Wong.jpg" },
  { author: "dusdin on flickr, cropped by Gridge", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Woman_redhead_natural_portrait_1.jpg" },
  { author: "Wendelin Jacober", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Portrait_with_natural_light_(Creative_Commons).jpg" },
  { author: "Pedro Ribeiro Simões from Lisboa, Portugal", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Woman_Photographer_(6872425924).jpg" },
  { author: "Shixart1985", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:A_happy_couple_embraces_each_other_outdoors,_laughing_and_enjoying_their_time_together.jpg" },
  { author: "Pasqualedifebbo", license: "CC BY 4.0", source: "https://commons.wikimedia.org/wiki/File:Sposi_che_ballano_con_gli_invitati_durante_la_festa.jpg" },
  { author: "Ferdinand Reus from Arnhem, Holland", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Smiling_woman,_The_Gambia_(March_2005).jpg" },
  { author: "rawpixel.com rawpixel", license: "CC0", source: "https://commons.wikimedia.org/wiki/File:Smiling_woman_with_a_phone_(Unsplash).jpg" },
  { author: "Joshua McKnight", license: "CC0", source: "https://commons.wikimedia.org/wiki/File:Smiling_woman_pink_shirt.jpg" },
  { author: "Leroy Skalstad", license: "CC0", source: "https://commons.wikimedia.org/wiki/File:Black_bearded_man_smiling,_2442565.jpg" },
];
